### ISSUE TITLE
Source Code?

### ISSUE THREAD

**Issue by DanteBeltran** [AgileIS/AgileTaskBoard#1]
Hi,

I would like to view source code for the SharePoint 2016 version of this app. but the zip file that I try to download does not contain any source code. is there any way I can view this version or if not a older release? please let me know! 

Thanks,

Dante Beltran

**Comment by huzlibuzli** [comment]
Hi Dante,
as already answered by e-mail, the Agile Task Board is a commercial product, so we cannot give you the source code for your own use. 

Bye, Boris
