### ISSUE TITLE
Is this a commercial product?

### ISSUE THREAD

**Issue by neocom-io** [AgileIS/AgileTaskBoard#2]
This repo/project is a bit confusing, you are using the MIT license and you have packaged sppkg files for 2016/2019 etc. and a source download with no source in it? Also I noticed after trying the 2019 package on my dev machine it has 'Trial Version' watermarked above the Kanban board. I think if this is a commercial product it should really be clearly stated on the front page and the releases page.

Overall it looks/works great and would work really well in a PnP Agile Project site template for example, but the fact it sends 'Telemetry' back and no source makes it a no go.

Edit--

Also just noticed.. It would also be worth letting people know on the front page it will not work without an internet connection, I noticed its pinging out for js files to azuredge.net even with telemetry off and will break with no internet access.

**Comment by huzlibuzli** [comment]
Thanks for your thoughts and suggestions. You're right the Agile Task Board is a commercial product, and we use this GitHub repo as a documentation and publishing channel for the software. I'll be making this clearer in the description in the near future and reviewing the license information to that effect. 

Telemetry can be turned off for each board instance. Loading the artifacts via our CDN is recommended according to the Microsoft described procedure for developing SPFx Web Parts. If your company needs a version with an internal CDN, please contact me and we will discuss the requirements. We are specialized in customizing solutions for our customers.
